### ISSUE TITLE
admin prefix

### ISSUE THREAD

**Issue by wu2kong** [xiaoxuan6/laravel-admin-env#1]
你好，目前后台地址如果不是默认的 admin 前缀的话，删除、搜索，批量删除目前都不可用
看了你的代码，目前是写死的 admin，是否可以增加读取 config/admin.php里面配置的前缀呢

**Comment by xiaoxuan6** [comment]
> 
> 
> 你好，目前后台地址如果不是默认的 admin 前缀的话，删除、搜索，批量删除目前都不可用
> 看了你的代码，目前是写死的 admin，是否可以增加读取 config/admin.php里面配置的前缀呢

更新到1.1.1 版本
